-- ============================================================
-- MIGRIN Control de Calidad - Seed de EETT por defecto
-- Ejecutar en el SQL Editor de Supabase (despues de eett-setup).
-- Publica en la tabla especificaciones las EETT que la app trae
-- programadas, para que las vistas de analisis las puedan leer.
-- ON CONFLICT DO NOTHING: NO pisa lo que ya hayas editado en Ajustes.
-- Generado desde calidad.html con gen-eett-seed.mjs
-- ============================================================

INSERT INTO especificaciones (producto_key, specs, updated_by) VALUES
('A36', '{"LIRQUEN":{"nombre":"Vidrios Lirquen","granulometria":{"#18":{"retAcumMax":0,"retAcumMin":null},"#25":{"retAcumMax":0.4,"retAcumMin":null},"#35":{"retAcumMax":2,"retAcumMin":null},"#120":{"retAcumMax":null,"retAcumMin":86},"#170":{"retAcumMax":null,"retAcumMin":95}},"d50Max":0.29,"quimica":{"SiO2":{"min":98.5,"max":null},"Al2O3":{"min":null,"max":0.2},"Fe2O3":{"min":null,"max":0.11}}},"CRISTALERIAS":{"nombre":"Cristalerias Chile","granulometria":{"#16":{"retAcumMax":0,"retAcumMin":null},"#20":{"retAcumMax":0,"retAcumMin":null},"#30":{"retAcumMax":0.1,"retAcumMin":null},"#100":{"retAcumMax":null,"retAcumMin":98.5}},"quimica":{"SiO2":{"min":94.3,"max":null},"Al2O3":{"min":2.2,"max":3},"Fe2O3":{"min":0.06,"max":0.12}}}}'::jsonb, 'seed-defaults'),
('A38', '{"nombre":"A38 Fierrillo","granulometria":{"#45":{"retMax":13,"retMin":null,"pasMax":null,"pasMin":null},"#60":{"retMax":27,"retMin":null,"pasMax":null,"pasMin":null},"#100":{"retMax":22,"retMin":null,"pasMax":null,"pasMin":null},"#170":{"retMax":28,"retMin":null,"pasMax":null,"pasMin":null},"#200":{"retMax":21,"retMin":null,"pasMax":null,"pasMin":null},"#400":{"retMax":22,"retMin":null,"pasMax":null,"pasMin":null},"+#40":{"retAcumMax":10,"retAcumMin":null},"-#400":{"pasMax":5,"pasMin":null},"#16":{"retMax":0,"retMin":null,"pasMax":null,"pasMin":null}},"quimica":{"SiO2":{"min":94,"max":100},"Al2O3":{"min":0.11,"max":0.23},"Fe2O3":{"min":0.1,"max":1.1},"CaO":{"min":null,"max":null},"MgO":{"min":null,"max":null},"K2O":{"min":null,"max":null},"Na2O":{"min":null,"max":null},"TiO2":{"min":null,"max":null}},"humedad":{"max":6}}'::jsonb, 'seed-defaults'),
('VERALTA', '{"granulometria":{"#20":{"retMax":0.1,"retMin":null,"pasMax":null,"pasMin":null},"#30":{"retMax":1.6,"retMin":null,"pasMax":null,"pasMin":null},"#140":{"retMax":null,"retMin":null,"pasMax":null,"pasMin":85},"#200":{"retMax":null,"retMin":null,"pasMax":null,"pasMin":98}},"quimica":{"SiO2":{"min":88,"max":null},"Al2O3":{"min":0.3,"max":0.45},"Fe2O3":{"min":null,"max":2},"CaO":{"min":null,"max":null},"MgO":{"min":null,"max":null},"K2O":{"min":null,"max":null},"Na2O":{"min":null,"max":null},"TiO2":{"min":null,"max":0.2},"K2O_Na2O":{"min":null,"max":2}},"humedad":{"max":5}}'::jsonb, 'seed-defaults'),
('VERBAJA', '{"granulometria":{"#20":{"retMax":0.1,"retMin":null,"pasMax":null,"pasMin":null},"#30":{"retMax":1.6,"retMin":null,"pasMax":null,"pasMin":null},"#140":{"retMax":null,"retMin":null,"pasMax":null,"pasMin":86},"#200":{"retMax":null,"retMin":null,"pasMax":null,"pasMin":98}},"quimica":{"SiO2":{"min":88.5,"max":null},"Al2O3":{"min":0.5,"max":2},"Fe2O3":{"min":null,"max":0.1},"CaO":{"min":null,"max":null},"MgO":{"min":null,"max":null},"K2O":{"min":null,"max":null},"Na2O":{"min":null,"max":null},"TiO2":{"min":null,"max":0.2},"K2O_Na2O":{"min":null,"max":2}},"humedad":{"max":5}}'::jsonb, 'seed-defaults'),
('CTLH', '{"granulometria":{"1\"":{"retMax":5,"retMin":null,"pasMax":null,"pasMin":null},"#6":{"retMax":null,"retMin":null,"pasMax":5,"pasMin":null}},"quimica":{"SiO2":{"min":97,"max":null},"Al2O3":{"min":null,"max":null},"Fe2O3":{"min":null,"max":null},"CaO":{"min":null,"max":null},"MgO":{"min":null,"max":null},"K2O":{"min":null,"max":null},"Na2O":{"min":null,"max":null},"TiO2":{"min":null,"max":null}},"humedad":{"max":2}}'::jsonb, 'seed-defaults'),
('CDLK', '{"granulometria":{"#6":{"retMax":0,"retMin":null,"pasMax":null,"pasMin":null},"#18":{"retMax":5,"retMin":null,"pasMax":null,"pasMin":null},"#400":{"retMax":null,"retMin":null,"pasMax":10,"pasMin":null}},"quimica":{"SiO2":{"min":94,"max":100},"Al2O3":{"min":0.05,"max":0.45},"Fe2O3":{"min":0.1,"max":0.7},"CaO":{"min":null,"max":null},"MgO":{"min":null,"max":null},"K2O":{"min":null,"max":null},"Na2O":{"min":null,"max":null},"TiO2":{"min":null,"max":null}},"humedad":{"max":7}}'::jsonb, 'seed-defaults'),
('DESP_LIR', '{"nombre":"Despacho Lirquen","granulometria":{"#18":{"retMax":0,"retMin":null,"pasMax":null,"pasMin":null},"#25":{"retMax":0.4,"retMin":null,"pasMax":null,"pasMin":null},"#35":{"retMax":2,"retMin":null,"pasMax":null,"pasMin":null},"#120":{"retMax":null,"retMin":86,"pasMax":null,"pasMin":null},"#170":{"retMax":null,"retMin":95,"pasMax":null,"pasMin":null}},"quimica":{"SiO2":{"min":98.5,"max":null},"Al2O3":{"min":null,"max":0.2},"Fe2O3":{"min":null,"max":0.11},"CaO":{"min":null,"max":null},"MgO":{"min":null,"max":null},"K2O":{"min":null,"max":null},"Na2O":{"min":null,"max":null},"TiO2":{"min":null,"max":null},"K2O_Na2O":{"min":null,"max":null}},"humedad":{"max":null},"d50Max":0.29}'::jsonb, 'seed-defaults'),
('DESP_PH', '{"granulometria":{"#20":{"retMax":0,"retMin":null,"pasMax":null,"pasMin":null},"#30":{"retMax":0.1,"retMin":null,"pasMax":null,"pasMin":null},"#100":{"retMax":null,"retMin":98.5,"pasMax":null,"pasMin":null}},"quimica":{"SiO2":{"min":94.3,"max":null},"Al2O3":{"min":2.2,"max":3},"Fe2O3":{"min":0.06,"max":0.12},"CaO":{"min":null,"max":null},"MgO":{"min":null,"max":null},"K2O":{"min":null,"max":null},"Na2O":{"min":null,"max":null},"TiO2":{"min":null,"max":null},"K2O_Na2O":{"min":null,"max":null}},"humedad":{"max":null}}'::jsonb, 'seed-defaults'),
('DESP_LLAY', '{"granulometria":{"#20":{"retMax":0,"retMin":null,"pasMax":null,"pasMin":null},"#30":{"retMax":0.1,"retMin":null,"pasMax":null,"pasMin":null},"#100":{"retMax":null,"retMin":98.5,"pasMax":null,"pasMin":null}},"quimica":{"SiO2":{"min":94.3,"max":null},"Al2O3":{"min":2.2,"max":3},"Fe2O3":{"min":0.06,"max":0.12},"CaO":{"min":null,"max":null},"MgO":{"min":null,"max":null},"K2O":{"min":null,"max":null},"Na2O":{"min":null,"max":null},"TiO2":{"min":null,"max":null},"K2O_Na2O":{"min":null,"max":null}},"humedad":{"max":null}}'::jsonb, 'seed-defaults'),
('TT_LODO', '{"granulometria":{"#120":{"retMax":10,"retMin":null,"pasMax":null,"pasMin":null}}}'::jsonb, 'seed-defaults')
ON CONFLICT (producto_key) DO NOTHING;
