-- ============================================================
-- MIGRIN Control de Calidad — Folio correlativo
-- Ejecutar en el SQL Editor de Supabase.
-- Agrega numero de muestra ascendente (1, 2, 3...) asignado
-- automaticamente por la base de datos al insertar.
-- Los registros existentes reciben folio segun su orden actual.
-- ============================================================

ALTER TABLE ensayos
  ADD COLUMN IF NOT EXISTS folio BIGINT GENERATED BY DEFAULT AS IDENTITY;

-- Reasignar folios existentes en orden cronologico de envio:
WITH ordenado AS (
  SELECT id, ROW_NUMBER() OVER (ORDER BY fecha_envio NULLS FIRST, hora_envio NULLS FIRST, id) AS rn
  FROM ensayos
)
UPDATE ensayos e SET folio = o.rn FROM ordenado o WHERE e.id = o.id;

-- Ajustar el contador para que el proximo folio continue la secuencia:
SELECT setval(
  pg_get_serial_sequence('ensayos','folio'),
  COALESCE((SELECT MAX(folio) FROM ensayos), 0) + 1,
  false
);
